name: Docker README
# Update the readme file for docker images when the description changes and is merged into main.
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - .github/workflows/docker_readme.yml
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/flashprint
          readme-filepath: README.md
          short-description: |
            A pre-configured Dockerfile for running FlashPrint in an isolated environment.
